name: "Deploy Python Greetings App"
description: "Composite action to deploy the Python Greetings App"
inputs:
  ENV_NAME:
    description: "The target environment for deployment"
    required: true
runs:
  using: "composite"
  steps:
    - name: Pull latest Docker image for Python Greetings App
      run: docker pull radud1337/python-greetings-app:latest
      shell: bash
    - name: Stop Service Container
      run: docker-compose stop greetings-app-${{ inputs.ENV_NAME }}
      shell: bash
    - name: Remove Service Container
      run: docker-compose rm -f greetings-app-${{ inputs.ENV_NAME }}
      shell: bash
    - name: Start Service Container
      run: docker-compose up -d greetings-app-${{ inputs.ENV_NAME }}
      shell: bash
