name: Build and Test Python Microservice pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-to-dev:
    runs-on: self-hosted
    needs: build-docker-image
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          ENV_NAME: "dev"

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    env:
      ENV_NAME: dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          ENV_NAME: "dev"

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          ENV_NAME: "stg"

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    env:
      ENV_NAME: stg
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          ENV_NAME: "stg"

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          ENV_NAME: "prod"

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    env:
      ENV_NAME: prod
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          ENV_NAME: "prod"
